package cn.spacexc.wearbili.remake.app.video.info.info.remote

data class Data(
    val aid: Long,
    val bvid: String,
    val cid: Long,
    val copyright: Int,
    val ctime: Int,
    val desc: String,
    val descV2: List<DescV2>,
    val dimension: Dimension,
    val duration: Int,
    val `dynamic`: String,
    val honorReply: HonorReply,
    val isChargeableSeason: Boolean,
    val isSeasonDisplay: Boolean,
    val isStory: Boolean,
    val likeIcon: String,
    val needJumpBv: Boolean,
    val noCache: Boolean,
    val owner: Owner,
    val pages: List<Page>,
    val pic: String,
    val premiere: Any,
    val pubdate: Long,
    val rights: Rights,
    val stat: Stat,
    val state: Int,
    val subtitle: Subtitles,
    val teenageMode: Int,
    val tid: Long,
    val title: String,
    val tname: String,
    val userGarb: UserGarb,
    val videos: Int
)